/*
 * OpenPodcast API
 * This is the OpenAPI specification for the OpenPodcast API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for FailedSubscription
 */
public class FailedSubscriptionTest {
    private final FailedSubscription model = new FailedSubscription();

    /**
     * Model tests for FailedSubscription
     */
    @Test
    public void testFailedSubscription() {
        // TODO: test FailedSubscription
    }

    /**
     * Test the property 'feedUrl'
     */
    @Test
    public void feedUrlTest() {
        // TODO: test feedUrl
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

}
