/*
 * OpenPodcast API
 * This is the OpenAPI specification for the OpenPodcast API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PatchedSubscription
 */
public class PatchedSubscriptionTest {
    private final PatchedSubscription model = new PatchedSubscription();

    /**
     * Model tests for PatchedSubscription
     */
    @Test
    public void testPatchedSubscription() {
        // TODO: test PatchedSubscription
    }

    /**
     * Test the property 'newFeedUrl'
     */
    @Test
    public void newFeedUrlTest() {
        // TODO: test newFeedUrl
    }

    /**
     * Test the property 'isSubscribed'
     */
    @Test
    public void isSubscribedTest() {
        // TODO: test isSubscribed
    }

    /**
     * Test the property 'subscriptionChanged'
     */
    @Test
    public void subscriptionChangedTest() {
        // TODO: test subscriptionChanged
    }

    /**
     * Test the property 'newGuid'
     */
    @Test
    public void newGuidTest() {
        // TODO: test newGuid
    }

    /**
     * Test the property 'guidChanged'
     */
    @Test
    public void guidChangedTest() {
        // TODO: test guidChanged
    }

}
