/*
 * OpenPodcast API
 * This is the OpenAPI specification for the OpenPodcast API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Subscription
 */
public class SubscriptionTest {
    private final Subscription model = new Subscription();

    /**
     * Model tests for Subscription
     */
    @Test
    public void testSubscription() {
        // TODO: test Subscription
    }

    /**
     * Test the property 'feedUrl'
     */
    @Test
    public void feedUrlTest() {
        // TODO: test feedUrl
    }

    /**
     * Test the property 'guid'
     */
    @Test
    public void guidTest() {
        // TODO: test guid
    }

    /**
     * Test the property 'isSubscribed'
     */
    @Test
    public void isSubscribedTest() {
        // TODO: test isSubscribed
    }

    /**
     * Test the property 'subscriptionChanged'
     */
    @Test
    public void subscriptionChangedTest() {
        // TODO: test subscriptionChanged
    }

    /**
     * Test the property 'newGuid'
     */
    @Test
    public void newGuidTest() {
        // TODO: test newGuid
    }

    /**
     * Test the property 'guidChanged'
     */
    @Test
    public void guidChangedTest() {
        // TODO: test guidChanged
    }

    /**
     * Test the property 'deleted'
     */
    @Test
    public void deletedTest() {
        // TODO: test deleted
    }

}
