/*
 * OpenPodcast API
 * This is the OpenAPI specification for the OpenPodcast API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.FailedSubscription;
import org.openapitools.client.model.NewSubscription;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * NewSubscriptions
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-07-17T20:17:50.894234-10:00[Pacific/Honolulu]", comments = "Generator version: 7.7.0")
public class NewSubscriptions {
  public static final String SERIALIZED_NAME_SUCCESS = "success";
  @SerializedName(SERIALIZED_NAME_SUCCESS)
  private List<NewSubscription> success = new ArrayList<>();

  public static final String SERIALIZED_NAME_FAILURE = "failure";
  @SerializedName(SERIALIZED_NAME_FAILURE)
  private List<FailedSubscription> failure = new ArrayList<>();

  public NewSubscriptions() {
  }

  public NewSubscriptions success(List<NewSubscription> success) {
    this.success = success;
    return this;
  }

  public NewSubscriptions addSuccessItem(NewSubscription successItem) {
    if (this.success == null) {
      this.success = new ArrayList<>();
    }
    this.success.add(successItem);
    return this;
  }

  /**
   * Get success
   * @return success
   */
  @javax.annotation.Nullable
  public List<NewSubscription> getSuccess() {
    return success;
  }

  public void setSuccess(List<NewSubscription> success) {
    this.success = success;
  }


  public NewSubscriptions failure(List<FailedSubscription> failure) {
    this.failure = failure;
    return this;
  }

  public NewSubscriptions addFailureItem(FailedSubscription failureItem) {
    if (this.failure == null) {
      this.failure = new ArrayList<>();
    }
    this.failure.add(failureItem);
    return this;
  }

  /**
   * Get failure
   * @return failure
   */
  @javax.annotation.Nullable
  public List<FailedSubscription> getFailure() {
    return failure;
  }

  public void setFailure(List<FailedSubscription> failure) {
    this.failure = failure;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NewSubscriptions newSubscriptions = (NewSubscriptions) o;
    return Objects.equals(this.success, newSubscriptions.success) &&
        Objects.equals(this.failure, newSubscriptions.failure);
  }

  @Override
  public int hashCode() {
    return Objects.hash(success, failure);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NewSubscriptions {\n");
    sb.append("    success: ").append(toIndentedString(success)).append("\n");
    sb.append("    failure: ").append(toIndentedString(failure)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("success");
    openapiFields.add("failure");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to NewSubscriptions
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!NewSubscriptions.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in NewSubscriptions is not found in the empty JSON string", NewSubscriptions.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!NewSubscriptions.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `NewSubscriptions` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("success") != null && !jsonObj.get("success").isJsonNull()) {
        JsonArray jsonArraysuccess = jsonObj.getAsJsonArray("success");
        if (jsonArraysuccess != null) {
          // ensure the json data is an array
          if (!jsonObj.get("success").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `success` to be an array in the JSON string but got `%s`", jsonObj.get("success").toString()));
          }

          // validate the optional field `success` (array)
          for (int i = 0; i < jsonArraysuccess.size(); i++) {
            NewSubscription.validateJsonElement(jsonArraysuccess.get(i));
          };
        }
      }
      if (jsonObj.get("failure") != null && !jsonObj.get("failure").isJsonNull()) {
        JsonArray jsonArrayfailure = jsonObj.getAsJsonArray("failure");
        if (jsonArrayfailure != null) {
          // ensure the json data is an array
          if (!jsonObj.get("failure").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `failure` to be an array in the JSON string but got `%s`", jsonObj.get("failure").toString()));
          }

          // validate the optional field `failure` (array)
          for (int i = 0; i < jsonArrayfailure.size(); i++) {
            FailedSubscription.validateJsonElement(jsonArrayfailure.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!NewSubscriptions.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'NewSubscriptions' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<NewSubscriptions> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(NewSubscriptions.class));

       return (TypeAdapter<T>) new TypeAdapter<NewSubscriptions>() {
           @Override
           public void write(JsonWriter out, NewSubscriptions value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public NewSubscriptions read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of NewSubscriptions given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of NewSubscriptions
   * @throws IOException if the JSON string is invalid with respect to NewSubscriptions
   */
  public static NewSubscriptions fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, NewSubscriptions.class);
  }

  /**
   * Convert an instance of NewSubscriptions to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

